version: "3.3"
services:
  devapp:
    image: streamlit-template-devapp
    build:
      dockerfile: Dockerfile
      context: .
      target: streamlit-template-devapp
    environment:
      PORT: 5000
    volumes:
      - ./app:/app/app
    ports:
      - "5050:5000"
  app:
    image: app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: 5000
    ports:
      - "5055:5000"
